### ISSUE TITLE
(Epic #10) Implement actor discovery for EsuAi

### ISSUE THREAD

**Issue by jsoberg** [jsoberg/ESU_OpenRA#11]
We need to find out how actors in the game can discover one another, and implement this method of discovery in the EsuAi. This will allow us to only "know" about the information that a human would, rather than having the entire world state available to us at all times.

**Comment by rmarmels** [comment]
Why not have the actors incrementally build their own "world state", adding to it as they discover things?  It could mimic the structure of the existing world state.

**Comment by jgreener79** [comment]
If we're playing fair, it needs to include the fog of war, where it knows the terrain, but not if there are any enemy troops present.

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by jsoberg** [comment]
Yea in essence I'd have to make my own "fog of war" for each actor, which would basically be the bounding area of the actor's units (to know what it can currently directly see) and some memory of what it has discovered (to know what it has seen previously).

**Comment by jsoberg** [comment]
Finding the 'visible area' for each individual actor is proving to be difficult; I thought that the VisualBounds field or the IDefaultVisibility field would prove to be useful for finding this area but they don't seem to be associated with the actor's visible range (e.g. as in how a Radar Dome has a higher visibility range than a rifle infantry soldier does).

**Comment by rmarmels** [comment]
Wrt, visible area, there is the below method that comes w/wo a radius:

internal Actor FindClosestEnemy(WPos pos, WDist radius)

If need be, different types of players could have different radii (e.g., infantry vs. aircraft) which would control how far they can "see".

**Comment by jsoberg** [comment]
I've implemented calculating the VisibilityBounds for all owned units, which allows for ascertaining what is visible to you currently. I'm going to make a separate ticket for scouting, as that will most likely take more effort.
