### ISSUE TITLE
Reduce time between ticks

### ISSUE THREAD

**Issue by jsoberg** [jsoberg/ESU_OpenRA#2]
We need to find a way to reduce the time between logic ticks (effectively reducing the time needed to complete a game).

**Comment by jsoberg** [comment]
This is effectively finished; If we find that we want to look at increasing the timestep further we can later on, but for now games without graphics are completed in ~1-4 minutes.

**Comment by rmarmels** [comment]
That should be perfect.

Date: Thu, 16 Jun 2016 06:03:15 -0700
