### ISSUE TITLE
(Epic #10) - Implement AmountOfResourcesToHaveBeforeNextProduction rule

### ISSUE THREAD

**Issue by jsoberg** [jsoberg/ESU_OpenRA#27]

**Comment by jsoberg** [comment]
Implement the AmountOfResourcesToHaveBeforeNextProduction rule, which determines the amount of resources to have on hand before we execute the next production.

**Comment by rmarmels** [comment]
I realize this is closed, but not sure why we even need this rule.  When most people play, they just issue order regardless of what resources are there or not.  

Date: Tue, 23 Aug 2016 18:18:15 -0700

**Comment by jgreener79** [comment]
Was this to try to make sure we didn't end up broke and having to sell buildings?

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by jsoberg** [comment]
It isn't necessary, but I found that once we started producing units we could producing 3 or more items at once, and would sometimes end up biting off more than we could chew for the moment (meaning we would need to wait longer for resources to arrive to finish building all of the items, rather than building them one or two at a time and receiving those items quicker). A 0 value would effectively turn this rule off.

**Comment by rmarmels** [comment]
I kind of recall a discussion about selling buildings to pay for higher priority items, but don't know what came of it.
Selling buildings is not always bad--sometimes it's necessary if you need the $$.  Especially if you have excess items like power plants or defensive structures.  I've often had to sell those things to replace an Ore refinery.

Date: Wed, 24 Aug 2016 10:54:57 -0700
